import type React from 'react';

// CUSTOM MODERN STYLES (Clean & Professional)
// Dipindah dari App.tsx apa adanya — isi & value SAMA PERSIS, cuma lokasinya beda.
export const styles: Record<string, React.CSSProperties> = {
  appWrapper: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: '#f1f5f9',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
  },
  sidebar: {
    width: '280px',
    backgroundColor: '#0f172a', // Dark Slate Modern
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    color: '#ffffff',
  },
  brandBox: { display: 'flex', alignItems: 'center', gap: '12px' },
  brandLogo: {
    width: '40px',
    height: '40px',
    backgroundColor: '#2563eb',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
  },
  brandTitle: { margin: 0, fontSize: '16px', letterSpacing: '0.5px' },
  brandSub: { margin: 0, fontSize: '11px', color: '#94a3b8' },
  studentCard: {
    backgroundColor: '#1e293b',
    padding: '12px',
    borderRadius: '12px',
    border: '1px solid #334155',
  },
  studentLabel: { fontSize: '10px', color: '#94a3b8', fontWeight: 'bold' },
  studentSelect: {
    width: '100%',
    marginTop: '6px',
    padding: '6px 8px',
    borderRadius: '6px',
    border: 'none',
    backgroundColor: '#0f172a',
    color: '#ffffff',
    fontSize: '12px',
    outline: 'none',
  },
  activeBio: {
    marginTop: '8px',
    backgroundColor: '#ffffff',
    padding: '8px',
    borderRadius: '6px',
  },
  navStack: { display: 'flex', flexDirection: 'column', gap: '8px' },
  navBtn: {
    padding: '10px 14px',
    borderRadius: '8px',
    border: 'none',
    color: '#ffffff',
    fontSize: '13px',
    fontWeight: '600',
    textAlign: 'left',
    cursor: 'pointer',
    transition: '0.2s',
  },
  mainContainer: { flex: 1, padding: '28px', overflowY: 'auto' },
  topHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    paddingBottom: '16px',
    borderBottom: '1px solid #e2e8f0',
  },
  badgeSemester: {
    backgroundColor: '#e0e7ff',
    color: '#4338ca',
    padding: '6px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: 'bold',
  },
  heroBanner: {
    backgroundColor: '#1e40af',
    borderRadius: '16px',
    padding: '24px',
    marginBottom: '24px',
  },
  sectionHeader: { fontSize: '16px', color: '#0f172a', marginBottom: '12px' },
  quickGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '16px' },
  quickCard: {
    backgroundColor: '#ffffff',
    padding: '16px',
    borderRadius: '12px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
    cursor: 'pointer',
  },
  dayTabRow: { display: 'flex', gap: '8px', marginBottom: '20px' },
  dayTabBtn: {
    padding: '8px 16px',
    borderRadius: '20px',
    border: '1px solid',
    fontWeight: 'bold',
    fontSize: '13px',
    cursor: 'pointer',
  },
  scheduleList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  scheduleCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    padding: '16px 20px',
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  },
  timeBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    borderRight: '2px dashed #cbd5e1',
    paddingRight: '20px',
  },
  jpBadge: {
    fontSize: '11px',
    backgroundColor: '#f1f5f9',
    padding: '2px 6px',
    borderRadius: '4px',
    marginTop: '4px',
  },
  examFilterContainer: { display: 'flex', flexDirection: 'column', gap: '12px', marginBottom: '20px' },
  semesterToggle: {
    display: 'flex',
    backgroundColor: '#e2e8f0',
    padding: '4px',
    borderRadius: '10px',
    width: 'fit-content',
  },
  semBtn: {
    padding: '6px 16px',
    borderRadius: '8px',
    border: 'none',
    fontWeight: 'bold',
    fontSize: '12px',
    cursor: 'pointer',
  },
  categoryPills: { display: 'flex', gap: '8px' },
  pillBtn: {
    padding: '8px 14px',
    borderRadius: '8px',
    border: '1px solid #cbd5e1',
    fontSize: '12px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  examGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '16px' },
  emptyExamBox: {
    backgroundColor: '#ffffff',
    padding: '24px',
    borderRadius: '12px',
    gridColumn: 'span 2',
    textAlign: 'center',
    color: '#64748b',
  },
  examCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    padding: '16px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
  },
  examBadge: {
    backgroundColor: '#eff6ff',
    color: '#2563eb',
    fontSize: '11px',
    fontWeight: 'bold',
    padding: '2px 8px',
    borderRadius: '4px',
  },
  scoreBox: {
    marginTop: '12px',
    paddingTop: '8px',
    borderTop: '1px solid #f1f5f9',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '12px',
  },
  presensiCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    padding: '20px',
  },
  statRow: { display: 'flex', gap: '24px', marginTop: '12px' },
  statBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    padding: '12px 24px',
    borderRadius: '8px',
  },
  teacherForm: {
    backgroundColor: '#ffffff',
    padding: '16px',
    borderRadius: '12px',
    marginBottom: '20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
  },
  chatInput: {
    flex: 1,
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1px solid #cbd5e1',
    fontSize: '13px',
    outline: 'none',
  },
  sendBtn: {
    backgroundColor: '#2563eb',
    color: '#ffffff',
    border: 'none',
    padding: '0 20px',
    borderRadius: '8px',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  chatList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  chatCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    padding: '16px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
  },
  broadcastTag: {
    display: 'inline-block',
    marginTop: '8px',
    backgroundColor: '#fef3c7',
    color: '#b45309',
    fontSize: '10px',
    fontWeight: 'bold',
    padding: '2px 8px',
    borderRadius: '4px',
  },
  statusBtnRow: { display: 'flex', gap: '8px', marginBottom: '12px' },
  statusBtn: { padding: '10px 20px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '13px', fontWeight: '600', cursor: 'pointer' },
  noteTextarea: { width: '100%', minHeight: '70px', padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '13px', outline: 'none', marginBottom: '12px', boxSizing: 'border-box', fontFamily: 'inherit', resize: 'vertical' },
  submitAttendanceBtn: { padding: '10px 20px', borderRadius: '8px', border: 'none', backgroundColor: '#2563eb', color: '#ffffff', fontWeight: 'bold', fontSize: '13px', cursor: 'pointer' },
};
